name: tms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  webview_flutter: ^2.0.13
  razorpay_flutter: ^1.3.4

  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  shared_preferences: ^2.0.0 # Added shared_preferences dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.0.13

flutter:
  uses-material-design: true

  assets:
    - assets/splash_screen.png
    - assets/temple1.png
    - assets/temple2.png
    - assets/temple3.png
